spring:
  application:
    name: ms-relationship

server:
  port: 8081

azure:
  cosmos:
    uri: https://brstudents-pucsp001.documents.azure.com:443/
    key: R1YXjA1tRFp9eSIy1ulwicjSHpZp6vwrFxpy6nTSjda6SOgDt4EJfaou3ebdkE7dQkNF93Y4QtwDdp5Qq5kWaQ==
    database: DB-RELATIONSHIP
    populate-query-metrics: false


